### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by JTanimations** [Er1cMa/Simple-Pomodoro-Timer#1]
Hello Er1c Ma , I am JT

Maybe we could work on projects together

(You know who i am right?)

**Comment by Er1cMa** [comment]
sure ok

**Comment by tzc-nydzsf** [comment]
JT has a Youtube!!! %%%

**Comment by tzc-nydzsf** [comment]
Both of you know python, but I don't/kk

**Comment by JTanimations** [comment]
？？？？peach？
